import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  // Loading
  loadingScreen: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    background: "#0b1120",
  },
  spinner: {
    width: 40,
    height: 40,
    border: "3px solid #374151",
    borderTop: "3px solid #fbbf24",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },

  // === AUTH PAGE ===
  authPage: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #0b1120 0%, #1a1a2e 50%, #16213e 100%)",
    position: "relative",
    overflow: "hidden",
  },
  authBgOrb1: {
    position: "absolute",
    width: "400px",
    height: "400px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(245,158,11,0.1) 0%, transparent 70%)",
    top: "-100px",
    right: "-100px",
    animation: "float 8s ease-in-out infinite",
  },
  authBgOrb2: {
    position: "absolute",
    width: "300px",
    height: "300px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(59,130,246,0.08) 0%, transparent 70%)",
    bottom: "-50px",
    left: "-50px",
    animation: "float 10s ease-in-out infinite reverse",
  },
  authCard: {
    width: "100%",
    maxWidth: "420px",
    padding: "40px",
    borderRadius: "20px",
    background: "rgba(31,41,55,0.7)",
    backdropFilter: "blur(24px)",
    border: "1px solid rgba(255,255,255,0.08)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
    zIndex: 1,
  },
  authLogoArea: {
    textAlign: "center" as const,
    marginBottom: "28px",
  },
  authLogo: {
    fontSize: "48px",
    marginBottom: "8px",
    animation: "float 4s ease-in-out infinite",
    display: "inline-block",
  },
  authTitle: {
    fontSize: "28px",
    fontWeight: 800,
    background: "linear-gradient(135deg, #fbbf24, #f59e0b, #d97706)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    letterSpacing: "-0.5px",
  },
  authSubtitle: {
    color: "#9ca3af",
    fontSize: "14px",
    marginTop: "4px",
  },
  tabContainer: {
    display: "flex",
    borderRadius: "12px",
    background: "rgba(17,24,39,0.6)",
    padding: "4px",
    marginBottom: "24px",
  },
  tab: {
    flex: 1,
    padding: "10px",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
    color: "#9ca3af",
    background: "transparent",
    transition: "all 0.2s",
    fontFamily: "inherit",
  },
  tabActive: {
    background: "rgba(245,158,11,0.15)",
    color: "#fbbf24",
  },
  authForm: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
    marginBottom: "8px",
  },
  inputLabel: {
    fontSize: "13px",
    fontWeight: 500,
    color: "#9ca3af",
  },
  input: {
    padding: "12px 14px",
    borderRadius: "10px",
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(17,24,39,0.6)",
    color: "#f3f4f6",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    fontFamily: "inherit",
    width: "100%",
  },
  errorBanner: {
    padding: "10px 14px",
    borderRadius: "10px",
    background: "rgba(239,68,68,0.12)",
    border: "1px solid rgba(239,68,68,0.3)",
    color: "#f87171",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  primaryBtn: {
    padding: "12px 24px",
    borderRadius: "10px",
    border: "none",
    background: "linear-gradient(135deg, #f59e0b, #d97706)",
    color: "#0b1120",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 0.2s",
    fontFamily: "inherit",
    letterSpacing: "0.3px",
  },

  // === DASHBOARD LAYOUT ===
  dashLayout: {
    display: "flex",
    minHeight: "100vh",
    background: "#0b1120",
  },

  // Sidebar
  sidebar: {
    width: "260px",
    background: "rgba(17,24,39,0.95)",
    borderRight: "1px solid rgba(255,255,255,0.06)",
    display: "flex",
    flexDirection: "column" as const,
    padding: "0",
    position: "sticky" as const,
    top: 0,
    height: "100vh",
    overflow: "hidden",
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "24px 20px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  sidebarLogo: {
    fontSize: "32px",
  },
  sidebarBrand: {
    fontSize: "18px",
    fontWeight: 800,
    background: "linear-gradient(135deg, #fbbf24, #d97706)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  sidebarVersion: {
    fontSize: "11px",
    color: "#6b7280",
    fontWeight: 500,
  },
  sidebarNav: {
    flex: 1,
    padding: "16px 12px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 14px",
    borderRadius: "10px",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 500,
    color: "#9ca3af",
    background: "transparent",
    transition: "all 0.2s",
    textAlign: "left" as const,
    fontFamily: "inherit",
  },
  navItemActive: {
    background: "rgba(245,158,11,0.1)",
    color: "#fbbf24",
  },
  navIcon: {
    fontSize: "18px",
  },
  sidebarFooter: {
    padding: "16px",
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  userBadge: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
  },
  userAvatar: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #f59e0b, #d97706)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    color: "#0b1120",
    fontSize: "16px",
  },
  userName: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#f3f4f6",
  },
  userRole: {
    fontSize: "11px",
    color: "#6b7280",
  },
  logoutBtn: {
    width: "100%",
    padding: "8px",
    borderRadius: "8px",
    border: "1px solid rgba(239,68,68,0.3)",
    background: "rgba(239,68,68,0.08)",
    color: "#f87171",
    fontSize: "13px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontWeight: 500,
    transition: "all 0.2s",
  },

  // Main content
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  topBar: {
    padding: "24px 32px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    background: "rgba(17,24,39,0.5)",
    backdropFilter: "blur(12px)",
  },
  pageTitle: {
    fontSize: "22px",
    fontWeight: 700,
    color: "#f3f4f6",
  },
  pageSubtitle: {
    fontSize: "13px",
    color: "#6b7280",
    marginTop: "4px",
  },
  contentArea: {
    flex: 1,
    padding: "28px 32px",
    overflowY: "auto" as const,
  },

  // KPI grid
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: "16px",
    marginBottom: "32px",
  },
  kpiCard: {
    padding: "20px",
    borderRadius: "14px",
    background: "rgba(31,41,55,0.6)",
    border: "1px solid rgba(255,255,255,0.06)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  kpiIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "20px",
  },
  kpiValue: {
    fontSize: "28px",
    fontWeight: 800,
    letterSpacing: "-1px",
  },
  kpiLabel: {
    fontSize: "13px",
    color: "#9ca3af",
    fontWeight: 500,
  },

  // Production grid
  prodGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: "14px",
    marginBottom: "32px",
  },
  prodCard: {
    padding: "18px",
    borderRadius: "12px",
    background: "rgba(31,41,55,0.5)",
    border: "1px solid rgba(255,255,255,0.06)",
    display: "flex",
    alignItems: "center",
    gap: "14px",
  },
  prodValue: {
    fontSize: "20px",
    fontWeight: 700,
  },
  prodLabel: {
    fontSize: "12px",
    color: "#9ca3af",
  },

  // Section title
  sectionTitle: {
    fontSize: "17px",
    fontWeight: 700,
    color: "#f3f4f6",
    marginBottom: "16px",
  },

  // Panel header
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    flexWrap: "wrap" as const,
    gap: "12px",
  },

  // Tables
  tableWrapper: {
    overflowX: "auto" as const,
    borderRadius: "12px",
    border: "1px solid rgba(255,255,255,0.06)",
    background: "rgba(31,41,55,0.4)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "13px",
  },
  th: {
    padding: "12px 16px",
    textAlign: "left" as const,
    background: "rgba(17,24,39,0.6)",
    fontWeight: 600,
    color: "#9ca3af",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    whiteSpace: "nowrap" as const,
  },
  tr: {
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    transition: "background 0.15s",
  },
  td: {
    padding: "10px 16px",
    color: "#d1d5db",
    whiteSpace: "nowrap" as const,
  },

  // Cards
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "16px",
  },
  apiaryCard: {
    padding: "20px",
    borderRadius: "14px",
    background: "rgba(31,41,55,0.6)",
    border: "1px solid rgba(255,255,255,0.08)",
    transition: "transform 0.2s, box-shadow 0.2s",
  },
  apiaryCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
  },
  apiaryName: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#f3f4f6",
  },
  apiaryMeta: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    fontSize: "13px",
    color: "#9ca3af",
    marginBottom: "16px",
  },
  apiaryActions: {
    display: "flex",
    gap: "8px",
  },
  cardBtnPrimary: {
    flex: 1,
    padding: "8px 14px",
    borderRadius: "8px",
    border: "none",
    background: "rgba(245,158,11,0.15)",
    color: "#fbbf24",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.2s",
  },
  cardBtnDanger: {
    padding: "8px 14px",
    borderRadius: "8px",
    border: "1px solid rgba(239,68,68,0.3)",
    background: "transparent",
    color: "#f87171",
    fontSize: "13px",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.2s",
  },

  // Colony card
  colonyCard: {
    padding: "20px",
    borderRadius: "14px",
    background: "rgba(31,41,55,0.6)",
    border: "1px solid rgba(255,255,255,0.08)",
    transition: "transform 0.2s",
  },
  colonyHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
  },
  statusDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
  },
  colonyCode: {
    fontSize: "16px",
    fontWeight: 700,
    color: "#f3f4f6",
    flex: 1,
  },
  statusBadge: {
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: 600,
  },
  colonyMeta: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    fontSize: "13px",
    color: "#9ca3af",
    marginBottom: "16px",
  },

  clearFilter: {
    marginLeft: "8px",
    padding: "2px 8px",
    borderRadius: "6px",
    border: "1px solid rgba(255,255,255,0.1)",
    background: "transparent",
    color: "#9ca3af",
    fontSize: "11px",
    cursor: "pointer",
    fontFamily: "inherit",
  },

  deleteBtnSmall: {
    padding: "4px 8px",
    borderRadius: "6px",
    border: "none",
    background: "rgba(239,68,68,0.1)",
    color: "#f87171",
    cursor: "pointer",
    fontSize: "14px",
  },

  // Empty state
  emptyState: {
    padding: "60px 20px",
    textAlign: "center" as const,
    color: "#6b7280",
    fontSize: "15px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "12px",
  },

  // Modal
  modalOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0,0,0,0.6)",
    backdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: "20px",
  },
  modalContent: {
    width: "100%",
    maxWidth: "520px",
    padding: "28px",
    borderRadius: "16px",
    background: "rgba(31,41,55,0.95)",
    border: "1px solid rgba(255,255,255,0.1)",
    boxShadow: "0 20px 60px rgba(0,0,0,0.6)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#f3f4f6",
  },
  modalClose: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: "none",
    background: "rgba(255,255,255,0.06)",
    color: "#9ca3af",
    cursor: "pointer",
    fontSize: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // Form section
  formSection: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#fbbf24",
    marginTop: "16px",
    marginBottom: "8px",
  },
};
