import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  // Loading
  loadingScreen: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    background: "var(--bg-app)",
  },
  spinner: {
    width: 40,
    height: 40,
    border: "3px solid var(--border-color)",
    borderTop: "3px solid var(--color-gold)",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },

  // === AUTH PAGE ===
  authPage: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, var(--bg-app) 0%, var(--bg-surface) 100%)",
    position: "relative",
    overflow: "hidden",
  },
  authBgOrb1: {
    position: "absolute",
    width: "400px",
    height: "400px",
    borderRadius: "50%",
    background: "radial-gradient(circle, var(--color-gold-glow) 0%, transparent 70%)",
    top: "-100px",
    right: "-100px",
    animation: "float 8s ease-in-out infinite",
  },
  authBgOrb2: {
    position: "absolute",
    width: "300px",
    height: "300px",
    borderRadius: "50%",
    background: "radial-gradient(circle, rgba(59,130,246,0.08) 0%, transparent 70%)",
    bottom: "-50px",
    left: "-50px",
    animation: "float 10s ease-in-out infinite reverse",
  },
  authCard: {
    width: "100%",
    maxWidth: "420px",
    padding: "40px",
    borderRadius: "20px",
    background: "var(--glass-bg)",
    backdropFilter: "var(--glass-blur)",
    border: "1px solid var(--glass-border)",
    boxShadow: "var(--shadow-lg)",
    zIndex: 1,
    color: "var(--text-main)",
  },
  authLogoArea: {
    textAlign: "center" as const,
    marginBottom: "28px",
  },
  authLogo: {
    fontSize: "48px",
    marginBottom: "8px",
    animation: "float 4s ease-in-out infinite",
    display: "inline-block",
  },
  authTitle: {
    fontSize: "28px",
    fontWeight: 800,
    background: "linear-gradient(135deg, var(--color-gold), var(--color-gold-hover))",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    letterSpacing: "-0.5px",
  },
  authSubtitle: {
    color: "var(--text-muted)",
    fontSize: "14px",
    marginTop: "4px",
  },
  tabContainer: {
    display: "flex",
    borderRadius: "12px",
    background: "var(--bg-app)",
    padding: "4px",
    marginBottom: "24px",
    border: "1px solid var(--border-color)",
  },
  tab: {
    flex: 1,
    padding: "10px",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "transparent",
    transition: "all 0.2s",
    fontFamily: "inherit",
  },
  tabActive: {
    background: "var(--color-gold-glow)",
    color: "var(--color-gold)",
  },
  authForm: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  inputGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
    marginBottom: "8px",
  },
  inputLabel: {
    fontSize: "13px",
    fontWeight: 500,
    color: "var(--text-muted)",
  },
  input: {
    padding: "12px 14px",
    borderRadius: "10px",
    border: "1px solid var(--border-color)",
    background: "var(--bg-surface)",
    color: "var(--text-main)",
    fontSize: "14px",
    outline: "none",
    transition: "border-color 0.2s",
    fontFamily: "inherit",
    width: "100%",
  },
  errorBanner: {
    padding: "10px 14px",
    borderRadius: "10px",
    background: "rgba(239,68,68,0.12)",
    border: "1px solid rgba(239,68,68,0.3)",
    color: "#f87171",
    fontSize: "13px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  primaryBtn: {
    padding: "12px 24px",
    borderRadius: "10px",
    border: "none",
    background: "linear-gradient(135deg, var(--color-gold), var(--color-gold-hover))",
    color: "#ffffff",
    fontSize: "15px",
    fontWeight: 700,
    cursor: "pointer",
    transition: "all 0.2s",
    fontFamily: "inherit",
    letterSpacing: "0.3px",
  },

  // === DASHBOARD LAYOUT ===
  dashLayout: {
    display: "flex",
    minHeight: "100vh",
    background: "var(--bg-app)",
    color: "var(--text-main)",
  },

  // Sidebar
  sidebar: {
    width: "260px",
    background: "var(--bg-surface)",
    borderRight: "1px solid var(--border-color)",
    display: "flex",
    flexDirection: "column" as const,
    padding: "0",
    position: "sticky" as const,
    top: 0,
    height: "100vh",
    overflow: "hidden",
  },
  sidebarHeader: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "24px 20px",
    borderBottom: "1px solid var(--border-color)",
  },
  sidebarLogo: {
    fontSize: "32px",
  },
  sidebarBrand: {
    fontSize: "18px",
    fontWeight: 800,
    background: "linear-gradient(135deg, var(--color-gold), var(--color-gold-hover))",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  sidebarVersion: {
    fontSize: "11px",
    color: "var(--text-muted)",
    fontWeight: 500,
  },
  sidebarNav: {
    flex: 1,
    padding: "16px 12px",
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    padding: "12px 14px",
    borderRadius: "10px",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: 500,
    color: "var(--text-muted)",
    background: "transparent",
    transition: "all 0.2s",
    textAlign: "left" as const,
    fontFamily: "inherit",
  },
  navItemActive: {
    background: "var(--color-gold-glow)",
    color: "var(--color-gold)",
    boxShadow: "var(--shadow-sm)",
  },
  navIcon: {
    fontSize: "18px",
  },
  sidebarFooter: {
    padding: "16px",
    borderTop: "1px solid var(--border-color)",
  },
  userBadge: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
  },
  userAvatar: {
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, var(--color-gold), var(--color-gold-hover))",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    color: "#ffffff",
    fontSize: "16px",
  },
  userName: {
    fontSize: "14px",
    fontWeight: 600,
    color: "var(--text-main)",
  },
  userRole: {
    fontSize: "11px",
    color: "var(--text-muted)",
  },
  logoutBtn: {
    width: "100%",
    padding: "8px",
    borderRadius: "8px",
    border: "1px solid rgba(239,68,68,0.3)",
    background: "rgba(239,68,68,0.08)",
    color: "#f87171",
    fontSize: "13px",
    cursor: "pointer",
    fontFamily: "inherit",
    fontWeight: 500,
    transition: "all 0.2s",
  },

  // Main content
  mainContent: {
    flex: 1,
    display: "flex",
    flexDirection: "column" as const,
    overflow: "hidden",
  },
  topBar: {
    padding: "24px 32px",
    borderBottom: "1px solid var(--border-color)",
    background: "var(--bg-surface)",
    backdropFilter: "var(--glass-blur)",
  },
  pageTitle: {
    fontSize: "22px",
    fontWeight: 700,
    color: "var(--text-main)",
  },
  pageSubtitle: {
    fontSize: "13px",
    color: "var(--text-muted)",
    marginTop: "4px",
  },
  contentArea: {
    flex: 1,
    padding: "28px 32px",
    overflowY: "auto" as const,
  },

  // KPI grid
  kpiGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(180px, 1fr))",
    gap: "16px",
    marginBottom: "32px",
  },
  kpiCard: {
    padding: "20px",
    borderRadius: "14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border-color)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    transition: "transform 0.2s, box-shadow 0.2s",
    boxShadow: "var(--shadow-sm)",
  },
  kpiIcon: {
    width: "40px",
    height: "40px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "20px",
  },
  kpiValue: {
    fontSize: "28px",
    fontWeight: 800,
    letterSpacing: "-1px",
  },
  kpiLabel: {
    fontSize: "13px",
    color: "var(--text-muted)",
    fontWeight: 500,
  },

  // Production grid
  prodGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: "14px",
    marginBottom: "32px",
  },
  prodCard: {
    padding: "18px",
    borderRadius: "12px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border-color)",
    display: "flex",
    alignItems: "center",
    gap: "14px",
    boxShadow: "var(--shadow-sm)",
  },
  prodValue: {
    fontSize: "20px",
    fontWeight: 700,
  },
  prodLabel: {
    fontSize: "12px",
    color: "var(--text-muted)",
  },

  // Section title
  sectionTitle: {
    fontSize: "17px",
    fontWeight: 700,
    color: "var(--text-main)",
    marginBottom: "16px",
  },

  // Panel header
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
    flexWrap: "wrap" as const,
    gap: "12px",
  },

  // Tables
  tableWrapper: {
    overflowX: "auto" as const,
    borderRadius: "12px",
    border: "1px solid var(--border-color)",
    background: "var(--bg-surface)",
    boxShadow: "var(--shadow-sm)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "13px",
  },
  th: {
    padding: "12px 16px",
    textAlign: "left" as const,
    background: "var(--bg-app)",
    fontWeight: 600,
    color: "var(--text-muted)",
    borderBottom: "1px solid var(--border-color)",
    whiteSpace: "nowrap" as const,
  },
  tr: {
    borderBottom: "1px solid var(--border-color)",
    transition: "background 0.15s",
  },
  td: {
    padding: "10px 16px",
    color: "var(--text-main)",
    whiteSpace: "nowrap" as const,
  },

  // Cards
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: "16px",
  },
  apiaryCard: {
    padding: "20px",
    borderRadius: "14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border-color)",
    transition: "transform 0.2s, box-shadow 0.2s",
    boxShadow: "var(--shadow-sm)",
  },
  apiaryCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
  },
  apiaryName: {
    fontSize: "16px",
    fontWeight: 700,
    color: "var(--text-main)",
  },
  apiaryMeta: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    fontSize: "13px",
    color: "var(--text-muted)",
    marginBottom: "16px",
  },
  apiaryActions: {
    display: "flex",
    gap: "8px",
  },
  cardBtnPrimary: {
    flex: 1,
    padding: "8px 14px",
    borderRadius: "8px",
    border: "none",
    background: "var(--color-gold-glow)",
    color: "var(--color-gold)",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.2s",
  },
  cardBtnDanger: {
    padding: "8px 14px",
    borderRadius: "8px",
    border: "1px solid rgba(239,68,68,0.3)",
    background: "transparent",
    color: "#f87171",
    fontSize: "13px",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all 0.2s",
  },

  // Colony card
  colonyCard: {
    padding: "20px",
    borderRadius: "14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border-color)",
    transition: "transform 0.2s",
    boxShadow: "var(--shadow-sm)",
  },
  colonyHeader: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "12px",
  },
  statusDot: {
    width: "10px",
    height: "10px",
    borderRadius: "50%",
  },
  colonyCode: {
    fontSize: "16px",
    fontWeight: 700,
    color: "var(--text-main)",
    flex: 1,
  },
  statusBadge: {
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: 600,
  },
  colonyMeta: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    fontSize: "13px",
    color: "var(--text-muted)",
    marginBottom: "16px",
  },

  clearFilter: {
    marginLeft: "8px",
    padding: "2px 8px",
    borderRadius: "6px",
    border: "1px solid var(--border-color)",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: "11px",
    cursor: "pointer",
    fontFamily: "inherit",
  },

  deleteBtnSmall: {
    padding: "4px 8px",
    borderRadius: "6px",
    border: "none",
    background: "rgba(239,68,68,0.1)",
    color: "#f87171",
    cursor: "pointer",
    fontSize: "14px",
  },

  // Empty state
  emptyState: {
    padding: "60px 20px",
    textAlign: "center" as const,
    color: "var(--text-muted)",
    fontSize: "15px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "12px",
  },

  // Modal
  modalOverlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(0,0,0,0.4)",
    backdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    zIndex: 1000,
    padding: "40px 20px",
    overflowY: "auto" as const,
  },
  modalContent: {
    width: "100%",
    maxWidth: "520px",
    padding: "28px",
    borderRadius: "16px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border-color)",
    boxShadow: "var(--shadow-lg)",
  },
  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "var(--text-main)",
  },
  modalClose: {
    width: "32px",
    height: "32px",
    borderRadius: "8px",
    border: "none",
    background: "var(--border-color)",
    color: "var(--text-muted)",
    cursor: "pointer",
    fontSize: "16px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // Form section
  formSection: {
    fontSize: "14px",
    fontWeight: 600,
    color: "var(--color-gold)",
    marginTop: "16px",
    marginBottom: "8px",
  },

  // === LANDING PAGE ===
  landingLayout: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, var(--bg-app) 0%, var(--bg-surface) 100%)",
    color: "var(--text-main)",
    fontFamily: "'Inter', sans-serif",
    display: "flex",
    flexDirection: "column",
  },
  landingHeader: {
    position: "sticky",
    top: 0,
    zIndex: 900,
    background: "var(--glass-bg)",
    backdropFilter: "var(--glass-blur)",
    WebkitBackdropFilter: "var(--glass-blur)",
    borderBottom: "1px solid var(--border-color)",
    padding: "16px 40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  landingLogo: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "20px",
    fontWeight: 800,
    background: "linear-gradient(135deg, var(--color-gold), var(--color-gold-hover))",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    cursor: "pointer",
  },
  landingNav: {
    display: "flex",
    alignItems: "center",
    gap: "28px",
  },
  landingNavLink: {
    background: "none",
    border: "none",
    color: "var(--text-muted)",
    fontSize: "14px",
    fontWeight: 500,
    cursor: "pointer",
    transition: "color 0.2s",
  },
  landingNavLinkActive: {
    color: "var(--color-gold)",
  },
  landingHeaderRight: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  roleBadge: {
    padding: "4px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: 700,
  },
  landingHero: {
    padding: "100px 20px 80px 20px",
    textAlign: "center",
    maxWidth: "960px",
    margin: "0 auto",
  },
  heroTitle: {
    fontSize: "48px",
    fontWeight: 800,
    lineHeight: 1.15,
    marginBottom: "24px",
    background: "linear-gradient(135deg, var(--text-main) 30%, var(--color-gold) 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    letterSpacing: "-1.5px",
  },
  heroSubtitle: {
    fontSize: "18px",
    color: "var(--text-muted)",
    lineHeight: 1.6,
    marginBottom: "40px",
    maxWidth: "760px",
    margin: "0 auto 40px auto",
  },
  heroActions: {
    display: "flex",
    justifyContent: "center",
    gap: "16px",
    flexWrap: "wrap",
  },
  btnGold: {
    padding: "14px 32px",
    borderRadius: "12px",
    border: "none",
    background: "linear-gradient(135deg, var(--color-gold), var(--color-gold-hover))",
    color: "#ffffff",
    fontSize: "16px",
    fontWeight: 700,
    cursor: "pointer",
    boxShadow: "var(--shadow-glow)",
    transition: "all 0.25s ease",
  },
  btnOutline: {
    padding: "14px 32px",
    borderRadius: "12px",
    border: "1px solid var(--border-color)",
    background: "rgba(0, 0, 0, 0.02)",
    color: "var(--text-main)",
    fontSize: "16px",
    fontWeight: 600,
    cursor: "pointer",
    transition: "all 0.25s ease",
  },
  landingSection: {
    padding: "80px 40px",
    borderTop: "1px solid var(--border-color)",
  },
  sectionHeaderLanding: {
    textAlign: "center" as const,
    marginBottom: "48px",
  },
  sectionTitlePre: {
    color: "var(--color-gold)",
    fontSize: "13px",
    fontWeight: 600,
    letterSpacing: "1px",
    textTransform: "uppercase",
    marginBottom: "8px",
  },
  sectionMainTitle: {
    fontSize: "32px",
    fontWeight: 800,
    color: "var(--text-main)",
    letterSpacing: "-0.5px",
  },
  landingGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "24px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  featureCard: {
    padding: "32px 24px",
    borderRadius: "16px",
    background: "var(--glass-bg)",
    backdropFilter: "var(--glass-blur)",
    border: "1px solid var(--glass-border)",
    boxShadow: "var(--shadow-sm)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    cursor: "pointer",
  },
  featureIcon: {
    fontSize: "36px",
    background: "var(--color-gold-glow)",
    width: "60px",
    height: "60px",
    borderRadius: "14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--color-gold)",
    marginBottom: "8px",
  },
  featureTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "var(--text-main)",
  },
  featureDesc: {
    fontSize: "13px",
    color: "var(--text-muted)",
    lineHeight: 1.5,
  },
  aboutContainer: {
    maxWidth: "1000px",
    margin: "0 auto",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "48px",
    alignItems: "center",
  },
  aboutText: {
    fontSize: "14px",
    color: "var(--text-main)",
    lineHeight: 1.7,
    display: "flex",
    flexDirection: "column" as const,
    gap: "16px",
  },
  aboutGraphic: {
    height: "260px",
    borderRadius: "16px",
    background: "linear-gradient(135deg, var(--color-gold-glow) 0%, rgba(59, 130, 246, 0.05) 100%)",
    border: "1px solid var(--border-color)",
    boxShadow: "inset 0 0 40px rgba(0, 0, 0, 0.02)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "72px",
    position: "relative",
  },
  landingFooter: {
    background: "var(--bg-surface)",
    borderTop: "1px solid var(--border-color)",
    padding: "40px",
    textAlign: "center" as const,
    fontSize: "13px",
    color: "var(--text-muted)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "12px",
  },
  // Modal Overlays
  modalBackdrop: {
    position: "fixed" as const,
    inset: 0,
    zIndex: 1000,
    background: "rgba(3, 7, 18, 0.4)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
  },
  modalBox: {
    position: "relative" as const,
    width: "100%",
    maxWidth: "420px",
    zIndex: 1001,
  },
  modalCloseBtn: {
    position: "absolute" as const,
    top: "-48px",
    right: "0",
    background: "var(--border-color)",
    border: "1px solid var(--border-color)",
    color: "var(--text-main)",
    width: "36px",
    height: "36px",
    borderRadius: "10px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    fontSize: "16px",
    transition: "all 0.2s",
  },
  // Infographics
  infographicGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "24px",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  infoCard: {
    padding: "32px 24px",
    borderRadius: "16px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border-color)",
    boxShadow: "var(--shadow-sm)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "12px",
    transition: "all 0.3s ease",
  },
  infoNumber: {
    fontSize: "36px",
    fontWeight: 800,
    background: "linear-gradient(135deg, var(--color-gold), #f97316)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  infoTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "var(--text-main)",
  },
  infoDesc: {
    fontSize: "13px",
    color: "var(--text-muted)",
    lineHeight: 1.6,
  },
  // Roadmap
  roadmapTimeline: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "32px",
    maxWidth: "800px",
    margin: "0 auto",
    position: "relative" as const,
  },
  roadmapItem: {
    display: "flex",
    gap: "24px",
    alignItems: "flex-start",
  },
  roadmapYearBadge: {
    background: "linear-gradient(135deg, var(--color-gold), #f97316)",
    color: "#ffffff",
    padding: "8px 16px",
    borderRadius: "20px",
    fontWeight: 800,
    fontSize: "14px",
    minWidth: "80px",
    textAlign: "center" as const,
    boxShadow: "var(--shadow-sm)",
  },
  roadmapCard: {
    flex: 1,
    padding: "24px",
    borderRadius: "14px",
    background: "var(--bg-surface)",
    border: "1px solid var(--border-color)",
    boxShadow: "var(--shadow-sm)",
  },
};
