from sqlalchemy.orm import Session
from sqlalchemy import func
from . import models, schemas
from .auth import get_password_hash


# ========== USER CRUD ==========

# --- Mappings & Helper for Autogenerated Pedigree Naming Standard ---
BREED_MAP = {
    "이탈리안": "IT", "Italian": "IT",
    "카니올란": "CA", "Carniolan": "CA",
    "코카시안": "CU", "Caucasian": "CU",
    "한봉": "KN", "Korean Native": "KN",
    "기타": "HY", "Hybrid": "HY"
}

REGION_MAP = {
    "서울": "SU", "seoul": "SU",
    "경기": "GG", "gyeonggi": "GG",
    "인천": "IC", "incheon": "IC",
    "강원": "GW", "gangwon": "GW",
    "충북": "CB", "충청북도": "CB",
    "충남": "CN", "충청남도": "CN",
    "대전": "DJ", "daejeon": "DJ",
    "세종": "SJ", "sejong": "SJ",
    "전북": "JB", "전라북도": "JB",
    "전남": "JN", "전라남도": "JN",
    "광주": "GJ", "gwangju": "GJ",
    "경북": "GB", "경상북도": "GB",
    "경남": "GN", "경상남도": "GN",
    "대구": "DG", "daegu": "DG",
    "울산": "US", "ulsan": "US",
    "부산": "BS", "busan": "BS",
    "제주": "JJ", "jeju": "JJ", "서귀포": "JJ"
}

def get_region_code(location: str) -> str:
    if not location:
        return "XX"
    for kw, code in REGION_MAP.items():
        if kw in location or kw.lower() in location.lower() or kw.replace(" ", "") in location.replace(" ", ""):
            return code
    return "XX"


def get_user_by_username(db: Session, username: str):
    return db.query(models.User).filter(models.User.username == username).first()

def create_user(db: Session, user: schemas.UserCreate) -> models.User:
    db_user = models.User(
        username=user.username,
        hashed_password=get_password_hash(user.password),
        farm_name=user.farm_name,
        role=user.role
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    
    # Auto-Onboarding: if initial_colony_count > 0, automatically seed 1 apiary and N colonies
    initial_count = getattr(user, "initial_colony_count", 0) or 0
    if initial_count > 0 and db_user.role == "farmer":
        # 1. Create Default Apiary
        apiary_name = f"{db_user.farm_name or db_user.username} 제1봉장"
        db_apiary = models.Apiary(
            name=apiary_name,
            owner=db_user.username,
            location="가입 온보딩 자동생성 봉장",
            latitude=37.5665,
            longitude=126.9780,
            owner_id=db_user.id
        )
        db.add(db_apiary)
        db.commit()
        db.refresh(db_apiary)
        
        # 2. Create N Colonies using Standard Regional Autogen Naming
        q_types = getattr(user, "queen_types", []) or []
        owner_initials = (db_user.username[:3].upper() + "XXX")[:3]
        region_code = get_region_code(db_apiary.location)
        
        for i in range(1, initial_count + 1):
            q_type = q_types[i - 1] if i - 1 < len(q_types) else "이탈리안"
            breed_code = BREED_MAP.get(q_type, "HY")
            
            c_code = f"C-{region_code}-{owner_initials}-26-01-{i:02d}"
            q_tag = f"Q-{breed_code}-{region_code}-26-{owner_initials}-{i:02d}"
            
            db_colony = models.Colony(
                code=c_code,
                apiary_id=db_apiary.id,
                status="Active",
                queen_tag=q_tag
            )
            db.add(db_colony)
        db.commit()
        db.refresh(db_user)
        
    return db_user


# ========== APIARY CRUD (owner-isolated) ==========

def get_apiary(db: Session, apiary_id: int, owner_id: int = None):
    q = db.query(models.Apiary).filter(models.Apiary.id == apiary_id)
    if owner_id is not None:
        q = q.filter(models.Apiary.owner_id == owner_id)
    return q.first()

def get_apiary_by_name(db: Session, name: str):
    return db.query(models.Apiary).filter(models.Apiary.name == name).first()

def get_apiaries(db: Session, skip: int = 0, limit: int = 100, owner_id: int = None):
    q = db.query(models.Apiary)
    if owner_id is not None:
        q = q.filter(models.Apiary.owner_id == owner_id)
    return q.offset(skip).limit(limit).all()

def create_apiary(db: Session, apiary: schemas.ApiaryCreate, owner_id: int = None):
    db_apiary = models.Apiary(
        name=apiary.name,
        owner=apiary.owner,
        location=apiary.location,
        latitude=apiary.latitude,
        longitude=apiary.longitude,
        owner_id=owner_id,
    )
    db.add(db_apiary)
    db.commit()
    db.refresh(db_apiary)
    return db_apiary

def delete_apiary(db: Session, apiary_id: int, owner_id: int = None):
    q = db.query(models.Apiary).filter(models.Apiary.id == apiary_id)
    if owner_id is not None:
        q = q.filter(models.Apiary.owner_id == owner_id)
    db_apiary = q.first()
    if db_apiary:
        db.delete(db_apiary)
        db.commit()
        return True
    return False


# ========== COLONY CRUD ==========

def get_colony(db: Session, colony_id: int):
    return db.query(models.Colony).filter(models.Colony.id == colony_id).first()

def get_colony_by_code(db: Session, code: str):
    return db.query(models.Colony).filter(models.Colony.code == code).first()

def get_colonies(db: Session, skip: int = 0, limit: int = 100, owner_id: int = None):
    q = db.query(models.Colony)
    if owner_id is not None:
        q = q.join(models.Apiary).filter(models.Apiary.owner_id == owner_id)
    return q.offset(skip).limit(limit).all()

def get_colonies_by_apiary(db: Session, apiary_id: int):
    return db.query(models.Colony).filter(models.Colony.apiary_id == apiary_id).all()

def create_colony(db: Session, colony: schemas.ColonyCreate):
    apiary = db.query(models.Apiary).filter(models.Apiary.id == colony.apiary_id).first()
    owner_username = "UNK"
    owner_id = None
    if apiary:
        owner_id = apiary.owner_id
        if apiary.owner_user:
            owner_username = apiary.owner_user.username
        else:
            owner_username = apiary.owner or "UNK"
            
    owner_initials = (owner_username[:3].upper() + "XXX")[:3]
    location = apiary.location if apiary else "Unknown"
    region_code = get_region_code(location)

    # 1. Resolve Colony Code if empty or 'Auto'
    c_code = colony.code
    if not c_code or c_code.strip() in ["", "Unknown", "Auto"]:
        # Find which apiary this is (index)
        apiary_count = db.query(models.Apiary).filter(
            models.Apiary.owner_id == owner_id,
            models.Apiary.id <= apiary.id
        ).count() if owner_id else 1
        apiary_no = f"{apiary_count:02d}"
        
        # Count colonies in this apiary
        colony_count = db.query(models.Colony).filter(
            models.Colony.apiary_id == colony.apiary_id
        ).count()
        colony_serial = f"{(colony_count + 1):02d}"
        
        c_code = f"C-{region_code}-{owner_initials}-26-{apiary_no}-{colony_serial}"

    # 2. Resolve Queen Tag if empty or 'Auto'
    q_tag = colony.queen_tag
    if not q_tag or q_tag.strip() in ["", "Unknown", "Auto"] or q_tag in BREED_MAP:
        breed_name = q_tag if q_tag and q_tag in BREED_MAP else "이탈리안"
        breed_code = BREED_MAP.get(breed_name, "HY")
        
        # Count total colonies (queens) for this owner
        queen_count = db.query(models.Colony).join(models.Apiary).filter(
            models.Apiary.owner_id == owner_id
        ).count() if owner_id else db.query(models.Colony).count()
        queen_serial = f"{(queen_count + 1):02d}"
        
        q_tag = f"Q-{breed_code}-{region_code}-26-{owner_initials}-{queen_serial}"

    db_colony = models.Colony(
        code=c_code,
        apiary_id=colony.apiary_id,
        status=colony.status,
        queen_tag=q_tag,
        mother_colony_id=colony.mother_colony_id
    )
    db.add(db_colony)
    db.commit()
    db.refresh(db_colony)
    return db_colony

def delete_colony(db: Session, colony_id: int):
    db_colony = db.query(models.Colony).filter(models.Colony.id == colony_id).first()
    if db_colony:
        db.delete(db_colony)
        db.commit()
        return True
    return False


# ========== TRAIT RECORD CRUD ==========

def get_trait_records(db: Session, skip: int = 0, limit: int = 100, owner_id: int = None):
    q = db.query(models.TraitRecord)
    if owner_id is not None:
        q = q.join(models.Colony).join(models.Apiary).filter(models.Apiary.owner_id == owner_id)
    return q.offset(skip).limit(limit).all()

def get_trait_records_by_colony(db: Session, colony_id: int):
    return db.query(models.TraitRecord).filter(
        models.TraitRecord.colony_id == colony_id
    ).order_by(models.TraitRecord.date.asc()).all()

def create_trait_record(db: Session, record: schemas.TraitRecordCreate):
    db_record = models.TraitRecord(
        colony_id=record.colony_id,
        date=record.date,
        honey_production=record.honey_production,
        propolis_production=record.propolis_production,
        royal_jelly_production=record.royal_jelly_production,
        temperament=record.temperament,
        virus_resistance=record.virus_resistance,
        mite_resistance=record.mite_resistance,
        swarming_rate=record.swarming_rate,
        overwintering_survival=record.overwintering_survival,
        climate_adaptation=record.climate_adaptation,
        temperature=record.temperature,
        humidity=record.humidity,
        vsh_rate=record.vsh_rate,
        hygienic_rate=record.hygienic_rate,
        notes=record.notes
    )
    db.add(db_record)
    db.commit()
    db.refresh(db_record)
    return db_record

def delete_trait_record(db: Session, record_id: int):
    db_record = db.query(models.TraitRecord).filter(models.TraitRecord.id == record_id).first()
    if db_record:
        db.delete(db_record)
        db.commit()
        return True
    return False


# ========== INTEGRATED DASHBOARD STATS (owner-isolated) ==========

def get_dashboard_statistics(db: Session, owner_id: int = None):
    """Return aggregated stats, optionally filtered by owner_id."""
    apiary_q = db.query(models.Apiary)
    colony_q = db.query(models.Colony)
    record_q = db.query(models.TraitRecord)

    if owner_id is not None:
        apiary_q = apiary_q.filter(models.Apiary.owner_id == owner_id)
        colony_q = colony_q.join(models.Apiary).filter(models.Apiary.owner_id == owner_id)
        record_q = record_q.join(models.Colony).join(models.Apiary).filter(models.Apiary.owner_id == owner_id)

    total_apiaries = apiary_q.count()
    total_colonies = colony_q.count()
    total_records = record_q.count()

    # Status breakdown
    active_q = colony_q.filter(models.Colony.status == "Active")
    weak_q = colony_q.filter(models.Colony.status == "Weak")
    dead_q = colony_q.filter(models.Colony.status == "Dead")
    active_count = active_q.count() if owner_id else db.query(models.Colony).filter(models.Colony.status == "Active").count()
    weak_count = weak_q.count() if owner_id else db.query(models.Colony).filter(models.Colony.status == "Weak").count()
    dead_count = dead_q.count() if owner_id else db.query(models.Colony).filter(models.Colony.status == "Dead").count()

    # Averages
    if owner_id:
        avg_honey = record_q.with_entities(func.avg(models.TraitRecord.honey_production)).scalar() or 0.0
        avg_propolis = record_q.with_entities(func.avg(models.TraitRecord.propolis_production)).scalar() or 0.0
        avg_royal_jelly = record_q.with_entities(func.avg(models.TraitRecord.royal_jelly_production)).scalar() or 0.0
        avg_survival = record_q.with_entities(func.avg(models.TraitRecord.overwintering_survival)).scalar() or 0.0
    else:
        avg_honey = db.query(func.avg(models.TraitRecord.honey_production)).scalar() or 0.0
        avg_propolis = db.query(func.avg(models.TraitRecord.propolis_production)).scalar() or 0.0
        avg_royal_jelly = db.query(func.avg(models.TraitRecord.royal_jelly_production)).scalar() or 0.0
        avg_survival = db.query(func.avg(models.TraitRecord.overwintering_survival)).scalar() or 0.0

    # Unique queen types
    queen_q = colony_q.with_entities(models.Colony.queen_tag).distinct()
    queen_types = queen_q.count() if owner_id else db.query(models.Colony.queen_tag).distinct().count()

    return {
        "total_apiaries": total_apiaries,
        "total_colonies": total_colonies,
        "total_records": total_records,
        "avg_honey": round(float(avg_honey), 2),
        "avg_propolis": round(float(avg_propolis), 2),
        "avg_royal_jelly": round(float(avg_royal_jelly), 2),
        "active_colonies": active_count,
        "weak_colonies": weak_count,
        "dead_colonies": dead_count,
        "avg_survival_rate": round(float(avg_survival), 2),
        "queen_types": queen_types,
    }


# ========== BULK SYNC CRUD (owner-isolated) ==========

def bulk_sync_data(db: Session, owner_id: int, payload: schemas.BulkSyncPayload) -> dict:
    created_apiaries_count = 0
    created_colonies_count = 0
    created_records_count = 0
    
    # 1. Process Apiaries
    apiary_name_to_id = {}
    for apiary in payload.apiaries:
        db_apiary = db.query(models.Apiary).filter(models.Apiary.name == apiary.name).first()
        if not db_apiary:
            db_apiary = models.Apiary(
                name=apiary.name,
                owner=apiary.owner,
                location=apiary.location,
                latitude=apiary.latitude,
                longitude=apiary.longitude,
                owner_id=owner_id
            )
            db.add(db_apiary)
            db.flush()  # populate ID
            created_apiaries_count += 1
        else:
            if db_apiary.owner_id != owner_id:
                # Security constraint: user cannot hijack an existing apiary name they don't own
                continue
        apiary_name_to_id[apiary.name] = db_apiary.id

    # 2. Process Colonies
    colony_code_to_id = {}
    colonies_to_update_parent = []
    for colony in payload.colonies:
        db_colony = db.query(models.Colony).filter(models.Colony.code == colony.code).first()
        if not db_colony:
            apiary_id = colony.apiary_id
            if not apiary_id and colony.apiary_name:
                apiary_id = apiary_name_to_id.get(colony.apiary_name)
                if not apiary_id:
                    exist_apiary = db.query(models.Apiary).filter(
                        models.Apiary.name == colony.apiary_name,
                        models.Apiary.owner_id == owner_id
                    ).first()
                    if exist_apiary:
                        apiary_id = exist_apiary.id
            
            if not apiary_id:
                continue
                
            db_colony = models.Colony(
                code=colony.code,
                apiary_id=apiary_id,
                status=colony.status,
                queen_tag=colony.queen_tag,
                mother_colony_id=colony.mother_colony_id
            )
            db.add(db_colony)
            db.flush()
            created_colonies_count += 1
        colony_code_to_id[colony.code] = db_colony.id
        if colony.mother_colony_code or colony.mother_colony_id:
            colonies_to_update_parent.append((db_colony, colony.mother_colony_id, colony.mother_colony_code))

    # 2-Pass: Resolve parent-child lineage for newly offline-created colonies
    for db_c, m_id, m_code in colonies_to_update_parent:
        resolved_id = m_id
        if not resolved_id and m_code:
            resolved_id = colony_code_to_id.get(m_code)
            if not resolved_id:
                exist_parent = db.query(models.Colony).join(models.Apiary).filter(
                    models.Colony.code == m_code,
                    models.Apiary.owner_id == owner_id
                ).first()
                if exist_parent:
                    resolved_id = exist_parent.id
        if resolved_id:
            db_c.mother_colony_id = resolved_id
            db.add(db_c)
            db.flush()

    # 3. Process Trait Records
    for record in payload.traits:
        colony_id = record.colony_id
        if not colony_id and record.colony_code:
            colony_id = colony_code_to_id.get(record.colony_code)
            if not colony_id:
                exist_colony = db.query(models.Colony).join(models.Apiary).filter(
                    models.Colony.code == record.colony_code,
                    models.Apiary.owner_id == owner_id
                ).first()
                if exist_colony:
                    colony_id = exist_colony.id
        
        if not colony_id:
            continue
            
        db_record = models.TraitRecord(
            colony_id=colony_id,
            date=record.date,
            honey_production=record.honey_production,
            propolis_production=record.propolis_production,
            royal_jelly_production=record.royal_jelly_production,
            temperament=record.temperament,
            virus_resistance=record.virus_resistance,
            mite_resistance=record.mite_resistance,
            swarming_rate=record.swarming_rate,
            overwintering_survival=record.overwintering_survival,
            climate_adaptation=record.climate_adaptation,
            temperature=record.temperature,
            humidity=record.humidity,
            vsh_rate=record.vsh_rate,
            hygienic_rate=record.hygienic_rate,
            notes=record.notes
        )
        db.add(db_record)
        created_records_count += 1
        
    db.commit()
    return {
        "success": True,
        "created_apiaries": created_apiaries_count,
        "created_colonies": created_colonies_count,
        "created_records": created_records_count
    }


# [DEPRECATED SEEDING - REMOVED TO PREVENT DUPLICATES]


# ========== MORPHOLOGICAL RECORD CRUD (Lab Research) ==========

def get_morphological_records(db: Session, skip: int = 0, limit: int = 100):
    return db.query(models.MorphologicalRecord).offset(skip).limit(limit).all()

def get_morphological_records_by_queen(db: Session, queen_tag: str):
    return db.query(models.MorphologicalRecord).filter(
        models.MorphologicalRecord.queen_tag == queen_tag
    ).order_by(models.MorphologicalRecord.date.asc()).all()

def create_morphological_record(db: Session, record: schemas.MorphologicalRecordCreate):
    db_record = models.MorphologicalRecord(
        queen_tag=record.queen_tag,
        colony_id=record.colony_id,
        date=record.date,
        cubital_index=record.cubital_index,
        proboscis_length=record.proboscis_length,
        tergite_color=record.tergite_color,
        basitarsus_length=record.basitarsus_length,
        basitarsus_width=record.basitarsus_width,
        researcher_notes=record.researcher_notes
    )
    db.add(db_record)
    db.commit()
    db.refresh(db_record)
    return db_record

def delete_morphological_record(db: Session, record_id: int):
    db_record = db.query(models.MorphologicalRecord).filter(models.MorphologicalRecord.id == record_id).first()
    if db_record:
        db.delete(db_record)
        db.commit()
        return True
    return False


# ========== DATA SEEDING ==========

def seed_database_if_empty(db: Session):
    # Ensure users exist (password hashing is applied)
    farmer1 = db.query(models.User).filter(models.User.username == "farmer1").first()
    if not farmer1:
        farmer1 = models.User(
            username="farmer1",
            hashed_password=get_password_hash("farmer1pass"),
            farm_name="지리산 육종 시험포",
            role="farmer"
        )
        db.add(farmer1)

    farmer2 = db.query(models.User).filter(models.User.username == "farmer2").first()
    if not farmer2:
        farmer2 = models.User(
            username="farmer2",
            hashed_password=get_password_hash("farmer2pass"),
            farm_name="강화도 협력 양봉장",
            role="farmer"
        )
        db.add(farmer2)

    researcher1 = db.query(models.User).filter(models.User.username == "researcher1").first()
    if not researcher1:
        researcher1 = models.User(
            username="researcher1",
            hashed_password=get_password_hash("researcher1pass"),
            farm_name="한국 꿀벌 유전학 연구실",
            role="researcher"
        )
        db.add(researcher1)

    admin = db.query(models.User).filter(models.User.username == "admin").first()
    if not admin:
        admin = models.User(
            username="admin",
            hashed_password=get_password_hash("adminpass"),
            farm_name="시스템 총괄 관리자",
            role="admin"
        )
        db.add(admin)

    db.commit()
    db.refresh(farmer1)
    db.refresh(farmer2)

    # Seed relational data if apiaries are empty
    if db.query(models.Apiary).count() > 0:
        return
    
    # 1. Create Apiaries
    apiary1 = models.Apiary(
        name="지리산포 제1봉장",
        owner="farmer1",
        location="경상남도 산청군 시천면",
        latitude=35.3369,
        longitude=127.7306,
        owner_id=farmer1.id
    )
    apiary2 = models.Apiary(
        name="강화포 제1봉장",
        owner="farmer2",
        location="인천광역시 강화군 화도면",
        latitude=37.6200,
        longitude=126.4700,
        owner_id=farmer2.id
    )
    db.add_all([apiary1, apiary2])
    db.commit()

    # 2. Create Colonies
    c1 = models.Colony(code="C-GN-FAR-26-01-01", apiary_id=apiary1.id, status="Active", queen_tag="Q-IT-GN-26-FAR-01")
    c2 = models.Colony(code="C-GN-FAR-26-01-02", apiary_id=apiary1.id, status="Active", queen_tag="Q-CA-GN-26-FAR-02")
    c3 = models.Colony(code="C-IC-FAR-26-01-01", apiary_id=apiary2.id, status="Active", queen_tag="Q-CU-IC-26-FAR-01")
    c4 = models.Colony(code="C-IC-FAR-26-01-02", apiary_id=apiary2.id, status="Weak", queen_tag="Q-HY-IC-26-FAR-02")
    db.add_all([c1, c2, c3, c4])
    db.commit()

    # 3. Create Trait Records (incorporating VSH and Hygienic behavior!)
    r1 = models.TraitRecord(colony_id=c1.id, date="2026-05-10", honey_production=48.5, propolis_production=330.0, royal_jelly_production=13.0, temperament=5, virus_resistance=5, mite_resistance=4, swarming_rate=10.0, overwintering_survival=95.0, climate_adaptation=5, temperature=22.0, humidity=60.0, vsh_rate=85.0, hygienic_rate=95.0, notes="채밀 성향 매우 좋음")
    r2 = models.TraitRecord(colony_id=c1.id, date="2026-05-20", honey_production=55.0, propolis_production=350.0, royal_jelly_production=16.0, temperament=5, virus_resistance=5, mite_resistance=5, swarming_rate=12.0, overwintering_survival=95.0, climate_adaptation=5, temperature=24.5, humidity=55.0, vsh_rate=90.0, hygienic_rate=98.0, notes="VSH 청결 활성 최상")
    r3 = models.TraitRecord(colony_id=c2.id, date="2026-05-12", honey_production=35.0, propolis_production=280.0, royal_jelly_production=7.5, temperament=4, virus_resistance=4, mite_resistance=3, swarming_rate=18.0, overwintering_survival=90.0, climate_adaptation=4, temperature=22.5, humidity=63.0, vsh_rate=65.0, hygienic_rate=80.0, notes="온순도 양호함")
    r4 = models.TraitRecord(colony_id=c3.id, date="2026-05-15", honey_production=42.0, propolis_production=300.0, royal_jelly_production=10.0, temperament=4, virus_resistance=4, mite_resistance=4, swarming_rate=15.0, overwintering_survival=92.0, climate_adaptation=4, temperature=20.0, humidity=70.0, vsh_rate=75.0, hygienic_rate=88.0, notes="강화도 해풍 기후 적응")
    r5 = models.TraitRecord(colony_id=c4.id, date="2026-05-16", honey_production=12.0, propolis_production=90.0, royal_jelly_production=1.5, temperament=2, virus_resistance=2, mite_resistance=2, swarming_rate=30.0, overwintering_survival=65.0, climate_adaptation=2, temperature=19.5, humidity=72.0, vsh_rate=35.0, hygienic_rate=45.0, notes="세력 미약, 봄철 사양 관리 보강 요망")
    db.add_all([r1, r2, r3, r4, r5])
    db.commit()

    # 4. Create Morphological Lab Samples (Seeding morphological values)
    morph1 = models.MorphologicalRecord(
        queen_tag="Q-IT-GN-26-FAR-01",
        colony_id=c1.id,
        date="2026-05-18",
        cubital_index=1.85,
        proboscis_length=6.45,
        tergite_color="Yellow-Stripes",
        basitarsus_length=3.25,
        basitarsus_width=1.15,
        researcher_notes="지리산 여왕벌 날개 및 구기 분석 완료"
    )
    morph2 = models.MorphologicalRecord(
        queen_tag="Q-CU-IC-26-FAR-01",
        colony_id=c3.id,
        date="2026-05-19",
        cubital_index=1.92,
        proboscis_length=6.30,
        tergite_color="Dark",
        basitarsus_length=3.15,
        basitarsus_width=1.10,
        researcher_notes="강화도 시료 분석 완료"
    )
    db.add_all([morph1, morph2])
    db.commit()

